export default [
  '/public/assets/images/01_Appartement_Rochard/02@2x.png',
  '/public/assets/images/01_Appartement_Rochard/03@2x.png',
  '/public/assets/images/01_Appartement_Rochard/04@2x.png',
  '/public/assets/images/01_Appartement_Rochard/05@2x.png',
  '/public/assets/images/01_Appartement_Rochard/06@2x.png',
  '/public/assets/images/01_Appartement_Rochard/07@2x.png',
  '/public/assets/images/02_Jaiye/01@2x.png',
  '/public/assets/images/02_Jaiye/02@2x.png',
  '/public/assets/images/02_Jaiye/03@2x.png',
  '/public/assets/images/02_Jaiye/04@2x.png',
  '/public/assets/images/02_Jaiye/05@2x.png',
  '/public/assets/images/02_Jaiye/06@2x.png',
  '/public/assets/images/02_Jaiye/07@2x.png',
  '/public/assets/images/02_Jaiye/08@2x.png',
  '/public/assets/images/02_Jaiye/09@2x.png',
  '/public/assets/images/02_Jaiye/10@2x.png',
  '/public/assets/images/02_Jaiye/11@2x.png',
  '/public/assets/images/02_Jaiye/12@2x.png',
  '/public/assets/images/02_Jaiye/13@2x.png',
  '/public/assets/images/03_DYLERZ/01_Homepage@2x.jpg',
  '/public/assets/images/03_DYLERZ/02_Menu_Events@2x.png',
  '/public/assets/images/03_DYLERZ/Group 6@2x.png',
  '/public/assets/images/03_DYLERZ/macbook@2x.png',
]
